language: python
python:
 - "2.7"
 - "3.6"
env:
    - TOX_ENV=py27-django111
    - TOX_ENV=py36-django111
    - TOX_ENV=py36-django20
install:
  - pip install tox
  - pip install "coverage>=3.7.1" coveralls
script: tox -e $TOX_ENV
after_success:
  - coverage report
  - coveralls
