language: python
python: 2.7
env:
    - TOX_ENV=py27-django19
    - TOX_ENV=py34-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py34-django110
install:
  - pip install tox
  - pip install "coverage>=3.7.1" coveralls
script: tox -e $TOX_ENV
after_success:
  - coverage report
  - coveralls
