sudo: false
language: python
python: "3.10"
env:
  matrix:
    - TOX_ENV=py310-django3213
    - TOX_ENV=py310-django404
matrix:
  fast_finish: true
install:
  - pip install tox
  - pip install "coverage>=3.7.1" coveralls
script: tox -e $TOX_ENV
after_success:
  - coverage report
  - coveralls
